# ---------------------------------------------------------
# Namespace
# ---------------------------------------------------------

apiVersion: v1
kind: Namespace
metadata:
  name: go-sample-microservice

---

# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-sample-app-deployment
  namespace: go-sample-microservice
spec:
  selector:
    matchLabels:
      app: prometheus-sample-app
  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: prometheus-sample-app
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: prometheus-sample-app
          image: qastudent/go-prometheus:1
         # image: prometheus-sample-app:latest
          imagePullPolicy: IfNotExists
          command:
            - "/main"
          args:
            - "--metric_count=30"
          ports:
            - containerPort: 8080